#ifndef CONSTANTE_H_INCLUDED
#define CONSTANTE_H_INCLUDED

#define Tamanho_Bloco  34

    enum{CIMA,BAIXO,ESQUERDA,DIREITA};
    enum{VAZIO,PAREDE,Bloco,Jogador1,Jogador2, BOMBA, EXPLOSAOB, EXPLOSAOC, EXPLOSAOD, EXPLOSAOE, EXPLOSAOM};


#endif // CONSTANTE_H_INCLUDED
