#ifndef CONSTANTE_H_INCLUDED
#define CONSTANTE_H_INCLUDED

#define TAMANHO_BLOCO  16

    enum{CIMA,BAIXO,ESQUERDA,DIREITA};
    enum{VAZIO,PAREDE,BLOCO,JOGADOR1,MAPA1};


#endif // CONSTANTE_H_INCLUDED
