#ifndef CONSTANTE_H_INCLUDED
#define CONSTANTE_H_INCLUDED

#define TAMANHO_BLOCO  34

    enum{CIMA,BAIXO,ESQUERDA,DIREITA};
    enum{VAZIO,PAREDE,BLOCO,JOGADOR1,JOGADOR2, BOMBA, EXPLOSAOB, EXPLOSAOC, EXPLOSAOD, EXPLOSAOE, EXPLOSAOM};


#endif // CONSTANTE_H_INCLUDED
